# Generated by Django 3.2.9 on 2021-11-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.FileField(blank=True, upload_to='songs'),
        ),
    ]
